# Generated by Django 5.0.6 on 2024-07-19 08:54

import django.contrib.postgres.fields.ranges
import django.contrib.postgres.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("book", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="StatusPercent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percentage_read_range",
                    django.contrib.postgres.fields.ranges.IntegerRangeField(
                        blank=True,
                        null=True,
                        validators=[
                            django.contrib.postgres.validators.RangeMinValueValidator(
                                0
                            ),
                            django.contrib.postgres.validators.RangeMaxValueValidator(
                                101
                            ),
                        ],
                    ),
                ),
                (
                    "read_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("reading", "Reading"),
                            ("done", "Done"),
                        ],
                        default="pending",
                        max_length=10,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Status Percentages",
            },
        ),
        migrations.CreateModel(
            name="MyRead",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "percentage_read",
                    models.PositiveSmallIntegerField(blank=True, null=True),
                ),
                ("start_read_date", models.DateField(blank=True, null=True)),
                ("end_read_date", models.DateField(blank=True, null=True)),
                (
                    "book_isbn",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="book.book"
                    ),
                ),
            ],
        ),
    ]
