# Generated by Django 5.0.6 on 2024-07-04 08:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("book", "0003_bookauthor"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="book",
            name="authors",
        ),
    ]
