# Generated by Django 5.0.6 on 2024-07-05 08:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0002_nic"),
    ]

    operations = [
        migrations.AddField(
            model_name="reader",
            name="nic",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reader",
                to="reader.nic",
            ),
        ),
    ]
