# Generated by Django 5.0.6 on 2024-07-10 09:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0003_reader_nic"),
    ]

    operations = [
        migrations.AlterModelTable(
            name="reader",
            table="reader",
        ),
    ]
