# Generated by Django 5.0.6 on 2024-07-10 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reader", "0004_alter_reader_table"),
    ]

    operations = [
        migrations.AlterModelTableComment(
            name="nic",
            table_comment="National Identity Card",
        ),
    ]
